/* Generated by re2c 0.14.3 */
#include "ext_scanners.h"
#include <stdlib.h>

bufsize_t _ext_scan_at(bufsize_t (*scanner)(const unsigned char *),
                       unsigned char *ptr, int len, bufsize_t offset) {
  bufsize_t res;

  if (ptr == NULL || offset > len) {
    return 0;
  } else {
    unsigned char lim = ptr[len];

    ptr[len] = '\0';
    res = scanner(ptr + offset);
    ptr[len] = lim;
  }

  return res;
}

bufsize_t _scan_table_start(const unsigned char *p) {
  const unsigned char *marker = NULL;
  const unsigned char *start = p;

  {
    unsigned char yych;
    static const unsigned char yybm[] = {
        0, 0,   0, 0, 0, 0, 0, 0, 0, 64, 0,  64, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0,   0, 0, 0, 0, 0, 0, 0, 0,  64, 0,  0,  0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 128, 0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0,   0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0,   0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0,   0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0,   0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0,   0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0,   0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0,   0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0,   0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0,   0, 0, 0, 0, 0, 0, 0, 0,  0,  0,  0,  0,
    };

    yych = *(marker = p);
    if (yych <= '{') {
      if (yych <= 0x1F) {
        if (yych <= '\t') {
          if (yych <= 0x08)
            goto yy6;
          goto yy3;
        } else {
          if (yych <= '\n')
            goto yy2;
          if (yych <= '\f')
            goto yy3;
          goto yy6;
        }
      } else {
        if (yych <= '-') {
          if (yych <= ' ')
            goto yy3;
          if (yych <= ',')
            goto yy6;
          goto yy5;
        } else {
          if (yych == ':')
            goto yy4;
          goto yy6;
        }
      }
    } else {
      if (yych <= 0xEC) {
        if (yych <= 0xC1) {
          if (yych <= '|')
            goto yy3;
          if (yych <= 0x7F)
            goto yy6;
        } else {
          if (yych <= 0xDF)
            goto yy7;
          if (yych <= 0xE0)
            goto yy9;
          goto yy10;
        }
      } else {
        if (yych <= 0xF0) {
          if (yych <= 0xED)
            goto yy14;
          if (yych <= 0xEF)
            goto yy10;
          goto yy11;
        } else {
          if (yych <= 0xF3)
            goto yy12;
          if (yych <= 0xF4)
            goto yy13;
        }
      }
    }
  yy2 : { return 0; }
  yy3:
    yych = *(marker = ++p);
    if (yybm[0 + yych] & 128) {
      goto yy22;
    }
    if (yych <= '\f') {
      if (yych == '\t')
        goto yy29;
      if (yych <= '\n')
        goto yy2;
      goto yy29;
    } else {
      if (yych <= ' ') {
        if (yych <= 0x1F)
          goto yy2;
        goto yy29;
      } else {
        if (yych == ':')
          goto yy31;
        goto yy2;
      }
    }
  yy4:
    yych = *(marker = ++p);
    if (yybm[0 + yych] & 128) {
      goto yy22;
    }
    goto yy2;
  yy5:
    yych = *(marker = ++p);
    if (yybm[0 + yych] & 128) {
      goto yy22;
    }
    if (yych <= ' ') {
      if (yych <= 0x08)
        goto yy2;
      if (yych <= '\r')
        goto yy16;
      if (yych <= 0x1F)
        goto yy2;
      goto yy16;
    } else {
      if (yych <= ':') {
        if (yych <= '9')
          goto yy2;
        goto yy15;
      } else {
        if (yych == '|')
          goto yy16;
        goto yy2;
      }
    }
  yy6:
    yych = *++p;
    goto yy2;
  yy7:
    yych = *++p;
    if (yych <= 0x7F)
      goto yy8;
    if (yych <= 0xBF)
      goto yy6;
  yy8:
    p = marker;
    goto yy2;
  yy9:
    yych = *++p;
    if (yych <= 0x9F)
      goto yy8;
    if (yych <= 0xBF)
      goto yy7;
    goto yy8;
  yy10:
    yych = *++p;
    if (yych <= 0x7F)
      goto yy8;
    if (yych <= 0xBF)
      goto yy7;
    goto yy8;
  yy11:
    yych = *++p;
    if (yych <= 0x8F)
      goto yy8;
    if (yych <= 0xBF)
      goto yy10;
    goto yy8;
  yy12:
    yych = *++p;
    if (yych <= 0x7F)
      goto yy8;
    if (yych <= 0xBF)
      goto yy10;
    goto yy8;
  yy13:
    yych = *++p;
    if (yych <= 0x7F)
      goto yy8;
    if (yych <= 0x8F)
      goto yy10;
    goto yy8;
  yy14:
    yych = *++p;
    if (yych <= 0x7F)
      goto yy8;
    if (yych <= 0x9F)
      goto yy7;
    goto yy8;
  yy15:
    ++p;
    yych = *p;
  yy16:
    if (yybm[0 + yych] & 64) {
      goto yy15;
    }
    if (yych <= '\r') {
      if (yych <= 0x08)
        goto yy8;
      if (yych <= '\n')
        goto yy20;
      goto yy19;
    } else {
      if (yych != '|')
        goto yy8;
    }
  yy17:
    ++p;
    yych = *p;
    if (yych <= 0x1F) {
      if (yych <= '\n') {
        if (yych <= 0x08)
          goto yy8;
        if (yych <= '\t')
          goto yy17;
        goto yy20;
      } else {
        if (yych <= '\f')
          goto yy17;
        if (yych >= 0x0E)
          goto yy8;
      }
    } else {
      if (yych <= '-') {
        if (yych <= ' ')
          goto yy17;
        if (yych <= ',')
          goto yy8;
        goto yy25;
      } else {
        if (yych == ':')
          goto yy24;
        goto yy8;
      }
    }
  yy19:
    yych = *++p;
    if (yych != '\n')
      goto yy8;
  yy20:
    ++p;
    { return (bufsize_t)(p - start); }
  yy22:
    ++p;
    yych = *p;
    if (yybm[0 + yych] & 128) {
      goto yy22;
    }
    if (yych <= 0x1F) {
      if (yych <= '\n') {
        if (yych <= 0x08)
          goto yy8;
        if (yych <= '\t')
          goto yy15;
        goto yy20;
      } else {
        if (yych <= '\f')
          goto yy15;
        if (yych <= '\r')
          goto yy19;
        goto yy8;
      }
    } else {
      if (yych <= ':') {
        if (yych <= ' ')
          goto yy15;
        if (yych <= '9')
          goto yy8;
        goto yy15;
      } else {
        if (yych == '|')
          goto yy17;
        goto yy8;
      }
    }
  yy24:
    ++p;
    yych = *p;
    if (yych != '-')
      goto yy8;
  yy25:
    ++p;
    yych = *p;
    if (yych <= ' ') {
      if (yych <= '\n') {
        if (yych <= 0x08)
          goto yy8;
        if (yych >= '\n')
          goto yy20;
      } else {
        if (yych <= '\f')
          goto yy27;
        if (yych <= '\r')
          goto yy19;
        if (yych <= 0x1F)
          goto yy8;
      }
    } else {
      if (yych <= '9') {
        if (yych == '-')
          goto yy25;
        goto yy8;
      } else {
        if (yych <= ':')
          goto yy27;
        if (yych == '|')
          goto yy17;
        goto yy8;
      }
    }
  yy27:
    ++p;
    yych = *p;
    if (yych <= '\r') {
      if (yych <= '\t') {
        if (yych <= 0x08)
          goto yy8;
        goto yy27;
      } else {
        if (yych <= '\n')
          goto yy20;
        if (yych <= '\f')
          goto yy27;
        goto yy19;
      }
    } else {
      if (yych <= ' ') {
        if (yych <= 0x1F)
          goto yy8;
        goto yy27;
      } else {
        if (yych == '|')
          goto yy17;
        goto yy8;
      }
    }
  yy29:
    ++p;
    yych = *p;
    if (yybm[0 + yych] & 128) {
      goto yy22;
    }
    if (yych <= '\f') {
      if (yych == '\t')
        goto yy29;
      if (yych <= '\n')
        goto yy8;
      goto yy29;
    } else {
      if (yych <= ' ') {
        if (yych <= 0x1F)
          goto yy8;
        goto yy29;
      } else {
        if (yych != ':')
          goto yy8;
      }
    }
  yy31:
    ++p;
    if (yybm[0 + (yych = *p)] & 128) {
      goto yy22;
    }
    goto yy8;
  }
}
